# Generated by Django 5.0 on 2023-12-30 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='fullname',
            field=models.CharField(max_length=255, verbose_name='Полное имя сотрудника'),
        ),
    ]
